// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Let schema.prisma read DATABASE_URL from env (shell or .env) so that
  // "DATABASE_URL=... npx prisma migrate deploy" works.
});
